First Video Lecture - (Intro to Javascript)
thatbeautifuldream/100xdocs pull request #11
Opened 2024-01-25 05:27 UTC by isuyashpatel

2024-01-25 06:09 UTC, thatbeautifuldream requested changes

2024-01-25 06:09 UTC, thatbeautifuldream commented on pages/docs/cohort-1/week-1/javascript.mdx
> +There are two types of data [Primitive and Non-Primitive](https://letmegooglethat.com/?q=primitive+and+non-primitive+data+types).
lets replace the letmegooglethat links with actual search queries for non-intrusive behaviour.

https://www.google.com/search?q=Primitive+and+Non-Primitive

2024-01-25 06:09 UTC, thatbeautifuldream commented on pages/docs/cohort-1/week-1/javascript.mdx
> +- [Single-threaded and Multi-threaded](https://letmegooglethat.com/?q=Single-threaded+and+Multi-threaded)
Please replace the link with : 

https://www.google.com/search?q=Single-threaded+and+Multi-threaded

2024-01-25 06:09 UTC, thatbeautifuldream commented on pages/docs/cohort-1/week-1/meta.json
> +    "basic-javascript": "Intro to Javascript"
Lets keep the titles and the url slug simmilar like if its Intro to Js lets keep the slug :

`intro-to-javasctipt`

2024-01-26 14:09 UTC, isuyashpatel commented
@thatbeautifuldream fixed

2024-01-27 03:59 UTC, thatbeautifuldream approved these changes
LGTM

2024-01-27 03:59 UTC, merged